### ISSUE TITLE
Have a problem with Progress Marker

### ISSUE THREAD

**Issue by Pommorale** [CG-Tespy/Fungus-Slot-based-Save-System#16]
Loader cannot be called/executed, it is already running. It happens when I keep Fade to View On. 
![Screen](https://user-images.githubusercontent.com/123302833/213916212-8d3c71f8-d401-40b3-acfb-a67d099a949a.png)

It's Normal State of my game:
![NormalGame](https://user-images.githubusercontent.com/123302833/213915720-a233c687-0f5c-4906-92c5-843f85377190.png)

When I try Load with Fade to View On:
![FadetoViewOn](https://user-images.githubusercontent.com/123302833/213915758-842b9c1b-4344-4072-a2ad-4c48072a3497.png)

When I try Load with Fade to View Off:
![FadetoViewOff](https://user-images.githubusercontent.com/123302833/213915770-3dc38aec-b2e5-435c-b207-9d28d1c21ddc.png)

Inspector New Block:
![InspectorNewBlock](https://user-images.githubusercontent.com/123302833/213915824-1bcf3cc4-7633-45e5-90cb-4f5f300cb9cf.png)

Inspector Loader:
![InspectorLoader](https://user-images.githubusercontent.com/123302833/213915838-a7029fd2-3dea-47bb-bc4c-6b1fe6a14f66.png)

Please, How I can fix it?

**Comment by CG-Tespy** [comment]
I'm going to need more help replicating this bug... Please give me instructions to do so. It'd probably help if you also sent me a project that has things set up

**Comment by Pommorale** [comment]
I'm so glad that you reacted so quickly!

I would also like to say that during the launch of the game, the check mark is removed from Saving Enabled. It stopped bothering me for a while, but it reappeared. "SaveManager's SaveManager is set to not add saves."

This is my project:
https://drive.google.com/drive/folders/1anPOfmLGwHEqWU7MDrOXmUxNlXmyG_Gu?usp=sharing

**Comment by CG-Tespy** [comment]
Sorry for not responding near as quick as I did before ^^; I'll be looking at the project you sent and get back to you

**Comment by CG-Tespy** [comment]
Alright, I did some digging and found some insights. 

1. The "Loader cannot be called/executed" shows up because for some reason, the save system tries to execute the same OnSaveDataLoaded block twice in a row. The second time is when it's already running. I don't think it's anything to worry about, but if it bothers you, please change OnSaveDataLoaded in the SaveDataLoaded script to this:

```
// If this has no keys, it acts as if it has the right one.
if (ProgressMarkerKeys.Length == 0)
{
    ExecuteBlock();
    return;
}

for (int i = 0; i < ProgressMarkerKeys.Length; i++)
{
    if (string.Compare(ProgressMarkerKeys[i], ProgressMarkerKey) == 0 &&
        !this.parentBlock.IsExecuting())
    {
        ExecuteBlock();
        break;
    }
}
```
^That should keep that warning message from showing up.

2. For some reason, the Fade To View Command in OnSaveDataLoaded makes the Block stop executing, which is why the Portrait Commands don't do anything. If you were to disable the former, the portraits do show up like you mentioned.

It seems like there's some incompatibility between Fade to View and the save system... I'll keep looking into that. As a side note, I never ran into the issue with the "SaveManager's SaveManager is set to not add saves." message when running your project.

**Comment by CG-Tespy** [comment]
Another update. Seems that for some reason, the fading coroutine just stops itself after the first yield return null, which then stops the rest of the OnSaveDataLoaded block from executing...

**Comment by CG-Tespy** [comment]
It might help if you send me a version of the project where the save UI is not directly tied to the Say Dialogs. For all we know, the Say Command could be part of the problem, but I can't even save the game when no Say Command is executing ^^;
